### ISSUE TITLE
Error when running 02_sparsify.py

### ISSUE THREAD

**Issue by BandarAA** [begab/sparsity_makes_sense#2]
First, thank you for this useful package,, I tried the demo and it seems it fits a new paper I'm working on.
However, whenever I run 02_sparsify.py the following error appears:
AttributeError: module '_spams_wrap' has no attribute 'L1COEFS_swigconstant'

Don't know what to do given I'm not an expert in python.
Thanks for your help.

**Comment by begab** [comment]
The error message relates to the SPAMS library, which is one of the external libraries our code base uses.
Can you verify if that library itself is properly installed?
You can follow the steps in the installation guides that you can found [here](https://gitlab.inria.fr/thoth/python-spams)

If you try to install that external package using `pip install spams` do you see any error messages?
After all, it might be the case that you need to install additional libraries so that SPAMS can be compiled on your machine. You can find the necessary libraries [here](https://gitlab.inria.fr/thoth/python-spams#comments).

**Comment by BandarAA** [comment]
Thank you begab. As you said, it's an issue related to SPAMS' installation. I re-installed, and everything is working very well now.
