### ISSUE TITLE
one letter words, tense of verbs

### ISSUE THREAD

**Issue by yishairasowsky** [begab/sparsity_makes_sense#3]
I put in the phrase "I read a book yesterday", and got some results that I didn't expect. Can I share with you some examples, in case you can share any insight? Thank you!

| Word      | What I would expect     | Actual demo result                         |
|-----------|-------------------------|--------------------------------------------|
| I         | first person pronoun    | symbol for either iodine or the number one |
| read      | past tense verb         | verb without indication of tense           |
| a         | indefinite article      | angstrom                                   |
| yesterday | the day preceding today | top choice: in the recent past             |

**Comment by begab** [comment]
The demo works by first checking WordNet, what synsets a word is related to, and then ranking those possibly related synsets.  
Since WordNet covers synsets of words that are either nouns, verbs, adjectives or adverbs, the correct sense for these one letter words are completely missing from WordNet, causing the above phenomenon.
You can check out the web interface of WordNet to see what [possible senses of the word 'I'](http://wordnetweb.princeton.edu/perl/webwn?s=i&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=) it includes.
